try {
  let a;
  console.log(a.lenght);
  console.log("hi from try statment");
} catch (e) {
  console.log("inside catch statement");
}

console.log("aruu");
